"use client";
import { useEffect, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
export interface PitchAnalytics { fours: number; sixes: number; wickets: number; }
export default function WagonWheel3D({ analytics, width = 520, height = 330 }: { analytics: PitchAnalytics; width?: number; height?: number }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const mount = ref.current; if (!mount) return; const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(width, height); mount.appendChild(renderer.domElement); const scene = new THREE.Scene(); const camera = new THREE.PerspectiveCamera(48, width / height, 0.1, 100); camera.position.set(11, 10, 15); const controls = new OrbitControls(camera, renderer.domElement); controls.target.set(0, 0, 0); controls.enablePan = false; controls.minDistance = 10; controls.maxDistance = 28; controls.update(); scene.add(new THREE.AmbientLight(0xffffff, 1.25)); const light = new THREE.DirectionalLight(0xffffff, 2); light.position.set(4, 10, 5); scene.add(light); const field = new THREE.Mesh(new THREE.CircleGeometry(8, 64), new THREE.MeshStandardMaterial({ color: 0x145a32, roughness: 0.75 })); field.rotation.x = -Math.PI / 2; scene.add(field); scene.add(new THREE.Mesh(new THREE.BoxGeometry(2.2, .15, 12), new THREE.MeshStandardMaterial({ color: 0xc89a5a })));
    const curve = (color: number, offset: number, heightArc: number) => { const c = new THREE.QuadraticBezierCurve3(new THREE.Vector3(0, .35, 4.7), new THREE.Vector3(offset * .55, heightArc, 0), new THREE.Vector3(offset, .3, -5.5)); scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(c.getPoints(40)), new THREE.LineBasicMaterial({ color, transparent: true, opacity: .95 }))); const tip = new THREE.Mesh(new THREE.SphereGeometry(.16, 12, 12), new THREE.MeshBasicMaterial({ color })); tip.position.set(offset, .3, -5.5); scene.add(tip); };
    for (let i = 0; i < Math.min(analytics.fours, 10); i++) curve(0xffff33, -6 + (i % 5) * 3, 2.2 + (i % 3)); for (let i = 0; i < Math.min(analytics.sixes, 8); i++) curve(0xffb300, -5 + (i % 4) * 3.3, 4.4 + (i % 3)); for (let i = 0; i < Math.min(analytics.wickets, 5); i++) curve(0xff304f, -3 + i * 1.5, 1.4);
    const particleMat = new THREE.MeshBasicMaterial({ color: 0x21d4fd }); [0, 1, 2].forEach((zone) => { for (let i = 0; i < 15; i++) { const p = new THREE.Mesh(new THREE.SphereGeometry(.07, 8, 8), particleMat); p.position.set(((i * 1.7) % 2) - 1, .2 + (i % 4) * .07, 4.5 - zone * 3.5 + (i % 5) * .25); scene.add(p); } }); let id = 0; const timer = new THREE.Timer(); timer.connect(document); const loop = (time: number) => { id = requestAnimationFrame(loop); timer.update(time); scene.rotation.y = Math.sin(timer.getElapsed() * .25) * .1; controls.update(); renderer.render(scene, camera); }; loop(performance.now()); return () => { cancelAnimationFrame(id); timer.disconnect(); timer.dispose(); controls.dispose(); renderer.dispose(); mount.removeChild(renderer.domElement); }; }, [analytics, width, height]);
  return <div ref={ref} style={{ width, maxWidth: "100%", height, borderRadius: 14, overflow: "hidden", background: "radial-gradient(circle, rgba(21,80,60,.55), rgba(4,12,24,.75))" }} />;
}
